package com.swjtu.roadCheck.mapper;

import com.swjtu.roadCheck.entity.Accidentdata;
import com.swjtu.roadCheck.entity.AccidentdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccidentdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int countByExample(AccidentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int deleteByExample(AccidentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int insert(Accidentdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int insertSelective(Accidentdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    List<Accidentdata> selectByExampleWithBLOBs(AccidentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    List<Accidentdata> selectByExample(AccidentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    Accidentdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Accidentdata record, @Param("example") AccidentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Accidentdata record, @Param("example") AccidentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Accidentdata record, @Param("example") AccidentdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Accidentdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Accidentdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidentdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Accidentdata record);
}