package com.swjtu.roadCheck.mapper;

import com.swjtu.roadCheck.entity.Accidencecollectiondata;
import com.swjtu.roadCheck.entity.AccidencecollectiondataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccidencecollectiondataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int countByExample(AccidencecollectiondataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int deleteByExample(AccidencecollectiondataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int insert(Accidencecollectiondata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int insertSelective(Accidencecollectiondata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    List<Accidencecollectiondata> selectByExampleWithBLOBs(AccidencecollectiondataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    List<Accidencecollectiondata> selectByExample(AccidencecollectiondataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    Accidencecollectiondata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Accidencecollectiondata record, @Param("example") AccidencecollectiondataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Accidencecollectiondata record, @Param("example") AccidencecollectiondataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Accidencecollectiondata record, @Param("example") AccidencecollectiondataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Accidencecollectiondata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Accidencecollectiondata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Accidencecollectiondata record);
}