package com.swjtu.roadCheck.mapper;

import com.swjtu.roadCheck.entity.Cardata;
import com.swjtu.roadCheck.entity.CardataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int countByExample(CardataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int deleteByExample(CardataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int insert(Cardata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int insertSelective(Cardata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    List<Cardata> selectByExampleWithBLOBs(CardataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    List<Cardata> selectByExample(CardataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    Cardata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Cardata record, @Param("example") CardataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Cardata record, @Param("example") CardataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Cardata record, @Param("example") CardataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cardata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Cardata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cardata record);
}