package com.swjtu.roadCheck.mapper;

import com.swjtu.roadCheck.entity.ChenzuoPeopelData;
import com.swjtu.roadCheck.entity.ChenzuoPeopelDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChenzuoPeopelDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int countByExample(ChenzuoPeopelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int deleteByExample(ChenzuoPeopelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int insert(ChenzuoPeopelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int insertSelective(ChenzuoPeopelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    List<ChenzuoPeopelData> selectByExample(ChenzuoPeopelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    ChenzuoPeopelData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChenzuoPeopelData record, @Param("example") ChenzuoPeopelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChenzuoPeopelData record, @Param("example") ChenzuoPeopelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChenzuoPeopelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenzuo_peopel_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChenzuoPeopelData record);
}