package com.swjtu.roadCheck.mapper;

import com.swjtu.roadCheck.entity.DriverPeoPelData;
import com.swjtu.roadCheck.entity.DriverPeoPelDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DriverPeoPelDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int countByExample(DriverPeoPelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int deleteByExample(DriverPeoPelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int insert(DriverPeoPelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int insertSelective(DriverPeoPelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    List<DriverPeoPelData> selectByExampleWithBLOBs(DriverPeoPelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    List<DriverPeoPelData> selectByExample(DriverPeoPelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    DriverPeoPelData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DriverPeoPelData record, @Param("example") DriverPeoPelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") DriverPeoPelData record, @Param("example") DriverPeoPelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DriverPeoPelData record, @Param("example") DriverPeoPelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DriverPeoPelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DriverPeoPelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_peo_pel_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DriverPeoPelData record);
}