package com.swjtu.roadCheck.mapper;

import com.swjtu.roadCheck.entity.Emdata;
import com.swjtu.roadCheck.entity.EmdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int countByExample(EmdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int deleteByExample(EmdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int insert(Emdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int insertSelective(Emdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    List<Emdata> selectByExampleWithBLOBs(EmdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    List<Emdata> selectByExample(EmdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    Emdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Emdata record, @Param("example") EmdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Emdata record, @Param("example") EmdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Emdata record, @Param("example") EmdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Emdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Emdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Emdata record);
}