package com.swjtu.roadCheck.entity;

import java.util.Date;

public class Accidencecollectiondata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata._id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.riqi
     *
     * @mbggenerated
     */
    private Date riqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.isUpload
     *
     * @mbggenerated
     */
    private Integer isupload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.admin_id
     *
     * @mbggenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.shigunumber
     *
     * @mbggenerated
     */
    private String shigunumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.place
     *
     * @mbggenerated
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.accidencenumber
     *
     * @mbggenerated
     */
    private String accidencenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.environmentnumber
     *
     * @mbggenerated
     */
    private String environmentnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.carnumber
     *
     * @mbggenerated
     */
    private String carnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accidencecollectiondata.peopelnumber
     *
     * @mbggenerated
     */
    private String peopelnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata._id
     *
     * @return the value of accidencecollectiondata._id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata._id
     *
     * @param id the value for accidencecollectiondata._id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.riqi
     *
     * @return the value of accidencecollectiondata.riqi
     *
     * @mbggenerated
     */
    public Date getRiqi() {
        return riqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.riqi
     *
     * @param riqi the value for accidencecollectiondata.riqi
     *
     * @mbggenerated
     */
    public void setRiqi(Date riqi) {
        this.riqi = riqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.isUpload
     *
     * @return the value of accidencecollectiondata.isUpload
     *
     * @mbggenerated
     */
    public Integer getIsupload() {
        return isupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.isUpload
     *
     * @param isupload the value for accidencecollectiondata.isUpload
     *
     * @mbggenerated
     */
    public void setIsupload(Integer isupload) {
        this.isupload = isupload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.admin_id
     *
     * @return the value of accidencecollectiondata.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.admin_id
     *
     * @param adminId the value for accidencecollectiondata.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.shigunumber
     *
     * @return the value of accidencecollectiondata.shigunumber
     *
     * @mbggenerated
     */
    public String getShigunumber() {
        return shigunumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.shigunumber
     *
     * @param shigunumber the value for accidencecollectiondata.shigunumber
     *
     * @mbggenerated
     */
    public void setShigunumber(String shigunumber) {
        this.shigunumber = shigunumber == null ? null : shigunumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.place
     *
     * @return the value of accidencecollectiondata.place
     *
     * @mbggenerated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.place
     *
     * @param place the value for accidencecollectiondata.place
     *
     * @mbggenerated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.accidencenumber
     *
     * @return the value of accidencecollectiondata.accidencenumber
     *
     * @mbggenerated
     */
    public String getAccidencenumber() {
        return accidencenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.accidencenumber
     *
     * @param accidencenumber the value for accidencecollectiondata.accidencenumber
     *
     * @mbggenerated
     */
    public void setAccidencenumber(String accidencenumber) {
        this.accidencenumber = accidencenumber == null ? null : accidencenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.environmentnumber
     *
     * @return the value of accidencecollectiondata.environmentnumber
     *
     * @mbggenerated
     */
    public String getEnvironmentnumber() {
        return environmentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.environmentnumber
     *
     * @param environmentnumber the value for accidencecollectiondata.environmentnumber
     *
     * @mbggenerated
     */
    public void setEnvironmentnumber(String environmentnumber) {
        this.environmentnumber = environmentnumber == null ? null : environmentnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.carnumber
     *
     * @return the value of accidencecollectiondata.carnumber
     *
     * @mbggenerated
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.carnumber
     *
     * @param carnumber the value for accidencecollectiondata.carnumber
     *
     * @mbggenerated
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accidencecollectiondata.peopelnumber
     *
     * @return the value of accidencecollectiondata.peopelnumber
     *
     * @mbggenerated
     */
    public String getPeopelnumber() {
        return peopelnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accidencecollectiondata.peopelnumber
     *
     * @param peopelnumber the value for accidencecollectiondata.peopelnumber
     *
     * @mbggenerated
     */
    public void setPeopelnumber(String peopelnumber) {
        this.peopelnumber = peopelnumber == null ? null : peopelnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", riqi=").append(riqi);
        sb.append(", isupload=").append(isupload);
        sb.append(", adminId=").append(adminId);
        sb.append(", shigunumber=").append(shigunumber);
        sb.append(", place=").append(place);
        sb.append(", accidencenumber=").append(accidencenumber);
        sb.append(", environmentnumber=").append(environmentnumber);
        sb.append(", carnumber=").append(carnumber);
        sb.append(", peopelnumber=").append(peopelnumber);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Accidencecollectiondata other = (Accidencecollectiondata) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRiqi() == null ? other.getRiqi() == null : this.getRiqi().equals(other.getRiqi()))
            && (this.getIsupload() == null ? other.getIsupload() == null : this.getIsupload().equals(other.getIsupload()))
            && (this.getAdminId() == null ? other.getAdminId() == null : this.getAdminId().equals(other.getAdminId()))
            && (this.getShigunumber() == null ? other.getShigunumber() == null : this.getShigunumber().equals(other.getShigunumber()))
            && (this.getPlace() == null ? other.getPlace() == null : this.getPlace().equals(other.getPlace()))
            && (this.getAccidencenumber() == null ? other.getAccidencenumber() == null : this.getAccidencenumber().equals(other.getAccidencenumber()))
            && (this.getEnvironmentnumber() == null ? other.getEnvironmentnumber() == null : this.getEnvironmentnumber().equals(other.getEnvironmentnumber()))
            && (this.getCarnumber() == null ? other.getCarnumber() == null : this.getCarnumber().equals(other.getCarnumber()))
            && (this.getPeopelnumber() == null ? other.getPeopelnumber() == null : this.getPeopelnumber().equals(other.getPeopelnumber()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accidencecollectiondata
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRiqi() == null) ? 0 : getRiqi().hashCode());
        result = prime * result + ((getIsupload() == null) ? 0 : getIsupload().hashCode());
        result = prime * result + ((getAdminId() == null) ? 0 : getAdminId().hashCode());
        result = prime * result + ((getShigunumber() == null) ? 0 : getShigunumber().hashCode());
        result = prime * result + ((getPlace() == null) ? 0 : getPlace().hashCode());
        result = prime * result + ((getAccidencenumber() == null) ? 0 : getAccidencenumber().hashCode());
        result = prime * result + ((getEnvironmentnumber() == null) ? 0 : getEnvironmentnumber().hashCode());
        result = prime * result + ((getCarnumber() == null) ? 0 : getCarnumber().hashCode());
        result = prime * result + ((getPeopelnumber() == null) ? 0 : getPeopelnumber().hashCode());
        return result;
    }
}