package com.swjtu.roadCheck.entity;

public class Cardata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata._id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.xunhao
     *
     * @mbggenerated
     */
    private Integer xunhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.carnumber
     *
     * @mbggenerated
     */
    private String carnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.vin
     *
     * @mbggenerated
     */
    private String vin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.chepaihao
     *
     * @mbggenerated
     */
    private String chepaihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.guobie
     *
     * @mbggenerated
     */
    private String guobie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.nianfen
     *
     * @mbggenerated
     */
    private String nianfen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.pingpai
     *
     * @mbggenerated
     */
    private String pingpai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.carType
     *
     * @mbggenerated
     */
    private String cartype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.Leixing
     *
     * @mbggenerated
     */
    private String leixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.cheneinum
     *
     * @mbggenerated
     */
    private String cheneinum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.tesuzuoyong
     *
     * @mbggenerated
     */
    private String tesuzuoyong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.xingshifangxing
     *
     * @mbggenerated
     */
    private String xingshifangxing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.Xingwei
     *
     * @mbggenerated
     */
    private String xingwei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.Jiechudian
     *
     * @mbggenerated
     */
    private String jiechudian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.sunhuaibuwei
     *
     * @mbggenerated
     */
    private String sunhuaibuwei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cardata.sunhuaschengdu
     *
     * @mbggenerated
     */
    private String sunhuaschengdu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata._id
     *
     * @return the value of cardata._id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata._id
     *
     * @param id the value for cardata._id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.xunhao
     *
     * @return the value of cardata.xunhao
     *
     * @mbggenerated
     */
    public Integer getXunhao() {
        return xunhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.xunhao
     *
     * @param xunhao the value for cardata.xunhao
     *
     * @mbggenerated
     */
    public void setXunhao(Integer xunhao) {
        this.xunhao = xunhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.carnumber
     *
     * @return the value of cardata.carnumber
     *
     * @mbggenerated
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.carnumber
     *
     * @param carnumber the value for cardata.carnumber
     *
     * @mbggenerated
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.vin
     *
     * @return the value of cardata.vin
     *
     * @mbggenerated
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.vin
     *
     * @param vin the value for cardata.vin
     *
     * @mbggenerated
     */
    public void setVin(String vin) {
        this.vin = vin == null ? null : vin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.chepaihao
     *
     * @return the value of cardata.chepaihao
     *
     * @mbggenerated
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.chepaihao
     *
     * @param chepaihao the value for cardata.chepaihao
     *
     * @mbggenerated
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao == null ? null : chepaihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.guobie
     *
     * @return the value of cardata.guobie
     *
     * @mbggenerated
     */
    public String getGuobie() {
        return guobie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.guobie
     *
     * @param guobie the value for cardata.guobie
     *
     * @mbggenerated
     */
    public void setGuobie(String guobie) {
        this.guobie = guobie == null ? null : guobie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.nianfen
     *
     * @return the value of cardata.nianfen
     *
     * @mbggenerated
     */
    public String getNianfen() {
        return nianfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.nianfen
     *
     * @param nianfen the value for cardata.nianfen
     *
     * @mbggenerated
     */
    public void setNianfen(String nianfen) {
        this.nianfen = nianfen == null ? null : nianfen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.pingpai
     *
     * @return the value of cardata.pingpai
     *
     * @mbggenerated
     */
    public String getPingpai() {
        return pingpai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.pingpai
     *
     * @param pingpai the value for cardata.pingpai
     *
     * @mbggenerated
     */
    public void setPingpai(String pingpai) {
        this.pingpai = pingpai == null ? null : pingpai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.carType
     *
     * @return the value of cardata.carType
     *
     * @mbggenerated
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.carType
     *
     * @param cartype the value for cardata.carType
     *
     * @mbggenerated
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.Leixing
     *
     * @return the value of cardata.Leixing
     *
     * @mbggenerated
     */
    public String getLeixing() {
        return leixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.Leixing
     *
     * @param leixing the value for cardata.Leixing
     *
     * @mbggenerated
     */
    public void setLeixing(String leixing) {
        this.leixing = leixing == null ? null : leixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.cheneinum
     *
     * @return the value of cardata.cheneinum
     *
     * @mbggenerated
     */
    public String getCheneinum() {
        return cheneinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.cheneinum
     *
     * @param cheneinum the value for cardata.cheneinum
     *
     * @mbggenerated
     */
    public void setCheneinum(String cheneinum) {
        this.cheneinum = cheneinum == null ? null : cheneinum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.tesuzuoyong
     *
     * @return the value of cardata.tesuzuoyong
     *
     * @mbggenerated
     */
    public String getTesuzuoyong() {
        return tesuzuoyong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.tesuzuoyong
     *
     * @param tesuzuoyong the value for cardata.tesuzuoyong
     *
     * @mbggenerated
     */
    public void setTesuzuoyong(String tesuzuoyong) {
        this.tesuzuoyong = tesuzuoyong == null ? null : tesuzuoyong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.xingshifangxing
     *
     * @return the value of cardata.xingshifangxing
     *
     * @mbggenerated
     */
    public String getXingshifangxing() {
        return xingshifangxing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.xingshifangxing
     *
     * @param xingshifangxing the value for cardata.xingshifangxing
     *
     * @mbggenerated
     */
    public void setXingshifangxing(String xingshifangxing) {
        this.xingshifangxing = xingshifangxing == null ? null : xingshifangxing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.Xingwei
     *
     * @return the value of cardata.Xingwei
     *
     * @mbggenerated
     */
    public String getXingwei() {
        return xingwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.Xingwei
     *
     * @param xingwei the value for cardata.Xingwei
     *
     * @mbggenerated
     */
    public void setXingwei(String xingwei) {
        this.xingwei = xingwei == null ? null : xingwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.Jiechudian
     *
     * @return the value of cardata.Jiechudian
     *
     * @mbggenerated
     */
    public String getJiechudian() {
        return jiechudian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.Jiechudian
     *
     * @param jiechudian the value for cardata.Jiechudian
     *
     * @mbggenerated
     */
    public void setJiechudian(String jiechudian) {
        this.jiechudian = jiechudian == null ? null : jiechudian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.sunhuaibuwei
     *
     * @return the value of cardata.sunhuaibuwei
     *
     * @mbggenerated
     */
    public String getSunhuaibuwei() {
        return sunhuaibuwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.sunhuaibuwei
     *
     * @param sunhuaibuwei the value for cardata.sunhuaibuwei
     *
     * @mbggenerated
     */
    public void setSunhuaibuwei(String sunhuaibuwei) {
        this.sunhuaibuwei = sunhuaibuwei == null ? null : sunhuaibuwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cardata.sunhuaschengdu
     *
     * @return the value of cardata.sunhuaschengdu
     *
     * @mbggenerated
     */
    public String getSunhuaschengdu() {
        return sunhuaschengdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cardata.sunhuaschengdu
     *
     * @param sunhuaschengdu the value for cardata.sunhuaschengdu
     *
     * @mbggenerated
     */
    public void setSunhuaschengdu(String sunhuaschengdu) {
        this.sunhuaschengdu = sunhuaschengdu == null ? null : sunhuaschengdu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", xunhao=").append(xunhao);
        sb.append(", carnumber=").append(carnumber);
        sb.append(", vin=").append(vin);
        sb.append(", chepaihao=").append(chepaihao);
        sb.append(", guobie=").append(guobie);
        sb.append(", nianfen=").append(nianfen);
        sb.append(", pingpai=").append(pingpai);
        sb.append(", cartype=").append(cartype);
        sb.append(", leixing=").append(leixing);
        sb.append(", cheneinum=").append(cheneinum);
        sb.append(", tesuzuoyong=").append(tesuzuoyong);
        sb.append(", xingshifangxing=").append(xingshifangxing);
        sb.append(", xingwei=").append(xingwei);
        sb.append(", jiechudian=").append(jiechudian);
        sb.append(", sunhuaibuwei=").append(sunhuaibuwei);
        sb.append(", sunhuaschengdu=").append(sunhuaschengdu);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Cardata other = (Cardata) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getXunhao() == null ? other.getXunhao() == null : this.getXunhao().equals(other.getXunhao()))
            && (this.getCarnumber() == null ? other.getCarnumber() == null : this.getCarnumber().equals(other.getCarnumber()))
            && (this.getVin() == null ? other.getVin() == null : this.getVin().equals(other.getVin()))
            && (this.getChepaihao() == null ? other.getChepaihao() == null : this.getChepaihao().equals(other.getChepaihao()))
            && (this.getGuobie() == null ? other.getGuobie() == null : this.getGuobie().equals(other.getGuobie()))
            && (this.getNianfen() == null ? other.getNianfen() == null : this.getNianfen().equals(other.getNianfen()))
            && (this.getPingpai() == null ? other.getPingpai() == null : this.getPingpai().equals(other.getPingpai()))
            && (this.getCartype() == null ? other.getCartype() == null : this.getCartype().equals(other.getCartype()))
            && (this.getLeixing() == null ? other.getLeixing() == null : this.getLeixing().equals(other.getLeixing()))
            && (this.getCheneinum() == null ? other.getCheneinum() == null : this.getCheneinum().equals(other.getCheneinum()))
            && (this.getTesuzuoyong() == null ? other.getTesuzuoyong() == null : this.getTesuzuoyong().equals(other.getTesuzuoyong()))
            && (this.getXingshifangxing() == null ? other.getXingshifangxing() == null : this.getXingshifangxing().equals(other.getXingshifangxing()))
            && (this.getXingwei() == null ? other.getXingwei() == null : this.getXingwei().equals(other.getXingwei()))
            && (this.getJiechudian() == null ? other.getJiechudian() == null : this.getJiechudian().equals(other.getJiechudian()))
            && (this.getSunhuaibuwei() == null ? other.getSunhuaibuwei() == null : this.getSunhuaibuwei().equals(other.getSunhuaibuwei()))
            && (this.getSunhuaschengdu() == null ? other.getSunhuaschengdu() == null : this.getSunhuaschengdu().equals(other.getSunhuaschengdu()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cardata
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getXunhao() == null) ? 0 : getXunhao().hashCode());
        result = prime * result + ((getCarnumber() == null) ? 0 : getCarnumber().hashCode());
        result = prime * result + ((getVin() == null) ? 0 : getVin().hashCode());
        result = prime * result + ((getChepaihao() == null) ? 0 : getChepaihao().hashCode());
        result = prime * result + ((getGuobie() == null) ? 0 : getGuobie().hashCode());
        result = prime * result + ((getNianfen() == null) ? 0 : getNianfen().hashCode());
        result = prime * result + ((getPingpai() == null) ? 0 : getPingpai().hashCode());
        result = prime * result + ((getCartype() == null) ? 0 : getCartype().hashCode());
        result = prime * result + ((getLeixing() == null) ? 0 : getLeixing().hashCode());
        result = prime * result + ((getCheneinum() == null) ? 0 : getCheneinum().hashCode());
        result = prime * result + ((getTesuzuoyong() == null) ? 0 : getTesuzuoyong().hashCode());
        result = prime * result + ((getXingshifangxing() == null) ? 0 : getXingshifangxing().hashCode());
        result = prime * result + ((getXingwei() == null) ? 0 : getXingwei().hashCode());
        result = prime * result + ((getJiechudian() == null) ? 0 : getJiechudian().hashCode());
        result = prime * result + ((getSunhuaibuwei() == null) ? 0 : getSunhuaibuwei().hashCode());
        result = prime * result + ((getSunhuaschengdu() == null) ? 0 : getSunhuaschengdu().hashCode());
        return result;
    }
}