package com.swjtu.roadCheck.entity;

public class Emdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata._id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.emnumber
     *
     * @mbggenerated
     */
    private String emnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.Routeposition
     *
     * @mbggenerated
     */
    private String routeposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.pengzhuangleixing
     *
     * @mbggenerated
     */
    private String pengzhuangleixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.liJiaoQuYu
     *
     * @mbggenerated
     */
    private String lijiaoquyu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.Jcktype
     *
     * @mbggenerated
     */
    private String jcktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.Teshuposition
     *
     * @mbggenerated
     */
    private String teshuposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.Tianqicondition
     *
     * @mbggenerated
     */
    private String tianqicondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.zhaomingcondition
     *
     * @mbggenerated
     */
    private String zhaomingcondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.luMianCondition
     *
     * @mbggenerated
     */
    private String lumiancondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.luMianLev
     *
     * @mbggenerated
     */
    private String lumianlev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.limitSpeed
     *
     * @mbggenerated
     */
    private String limitspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.chedaowidth
     *
     * @mbggenerated
     */
    private String chedaowidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.luJianWidth
     *
     * @mbggenerated
     */
    private String lujianwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.bianYuanXianle
     *
     * @mbggenerated
     */
    private String bianyuanxianle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.zhongyanwidht
     *
     * @mbggenerated
     */
    private String zhongyanwidht;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.zhongXinXian
     *
     * @mbggenerated
     */
    private String zhongxinxian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.chedaoxianbj
     *
     * @mbggenerated
     */
    private String chedaoxianbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.jiaotongkzlx
     *
     * @mbggenerated
     */
    private String jiaotongkzlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.zhuchedaoshu
     *
     * @mbggenerated
     */
    private String zhuchedaoshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.jiaochajiedaoshu
     *
     * @mbggenerated
     */
    private String jiaochajiedaoshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.WorkPlaceR
     *
     * @mbggenerated
     */
    private String workplacer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.Worktype
     *
     * @mbggenerated
     */
    private String worktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.havepeople
     *
     * @mbggenerated
     */
    private String havepeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emdata.xianChangZhifa
     *
     * @mbggenerated
     */
    private String xianchangzhifa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata._id
     *
     * @return the value of emdata._id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata._id
     *
     * @param id the value for emdata._id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.emnumber
     *
     * @return the value of emdata.emnumber
     *
     * @mbggenerated
     */
    public String getEmnumber() {
        return emnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.emnumber
     *
     * @param emnumber the value for emdata.emnumber
     *
     * @mbggenerated
     */
    public void setEmnumber(String emnumber) {
        this.emnumber = emnumber == null ? null : emnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.Routeposition
     *
     * @return the value of emdata.Routeposition
     *
     * @mbggenerated
     */
    public String getRouteposition() {
        return routeposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.Routeposition
     *
     * @param routeposition the value for emdata.Routeposition
     *
     * @mbggenerated
     */
    public void setRouteposition(String routeposition) {
        this.routeposition = routeposition == null ? null : routeposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.pengzhuangleixing
     *
     * @return the value of emdata.pengzhuangleixing
     *
     * @mbggenerated
     */
    public String getPengzhuangleixing() {
        return pengzhuangleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.pengzhuangleixing
     *
     * @param pengzhuangleixing the value for emdata.pengzhuangleixing
     *
     * @mbggenerated
     */
    public void setPengzhuangleixing(String pengzhuangleixing) {
        this.pengzhuangleixing = pengzhuangleixing == null ? null : pengzhuangleixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.liJiaoQuYu
     *
     * @return the value of emdata.liJiaoQuYu
     *
     * @mbggenerated
     */
    public String getLijiaoquyu() {
        return lijiaoquyu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.liJiaoQuYu
     *
     * @param lijiaoquyu the value for emdata.liJiaoQuYu
     *
     * @mbggenerated
     */
    public void setLijiaoquyu(String lijiaoquyu) {
        this.lijiaoquyu = lijiaoquyu == null ? null : lijiaoquyu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.Jcktype
     *
     * @return the value of emdata.Jcktype
     *
     * @mbggenerated
     */
    public String getJcktype() {
        return jcktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.Jcktype
     *
     * @param jcktype the value for emdata.Jcktype
     *
     * @mbggenerated
     */
    public void setJcktype(String jcktype) {
        this.jcktype = jcktype == null ? null : jcktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.Teshuposition
     *
     * @return the value of emdata.Teshuposition
     *
     * @mbggenerated
     */
    public String getTeshuposition() {
        return teshuposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.Teshuposition
     *
     * @param teshuposition the value for emdata.Teshuposition
     *
     * @mbggenerated
     */
    public void setTeshuposition(String teshuposition) {
        this.teshuposition = teshuposition == null ? null : teshuposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.Tianqicondition
     *
     * @return the value of emdata.Tianqicondition
     *
     * @mbggenerated
     */
    public String getTianqicondition() {
        return tianqicondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.Tianqicondition
     *
     * @param tianqicondition the value for emdata.Tianqicondition
     *
     * @mbggenerated
     */
    public void setTianqicondition(String tianqicondition) {
        this.tianqicondition = tianqicondition == null ? null : tianqicondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.zhaomingcondition
     *
     * @return the value of emdata.zhaomingcondition
     *
     * @mbggenerated
     */
    public String getZhaomingcondition() {
        return zhaomingcondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.zhaomingcondition
     *
     * @param zhaomingcondition the value for emdata.zhaomingcondition
     *
     * @mbggenerated
     */
    public void setZhaomingcondition(String zhaomingcondition) {
        this.zhaomingcondition = zhaomingcondition == null ? null : zhaomingcondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.luMianCondition
     *
     * @return the value of emdata.luMianCondition
     *
     * @mbggenerated
     */
    public String getLumiancondition() {
        return lumiancondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.luMianCondition
     *
     * @param lumiancondition the value for emdata.luMianCondition
     *
     * @mbggenerated
     */
    public void setLumiancondition(String lumiancondition) {
        this.lumiancondition = lumiancondition == null ? null : lumiancondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.luMianLev
     *
     * @return the value of emdata.luMianLev
     *
     * @mbggenerated
     */
    public String getLumianlev() {
        return lumianlev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.luMianLev
     *
     * @param lumianlev the value for emdata.luMianLev
     *
     * @mbggenerated
     */
    public void setLumianlev(String lumianlev) {
        this.lumianlev = lumianlev == null ? null : lumianlev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.limitSpeed
     *
     * @return the value of emdata.limitSpeed
     *
     * @mbggenerated
     */
    public String getLimitspeed() {
        return limitspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.limitSpeed
     *
     * @param limitspeed the value for emdata.limitSpeed
     *
     * @mbggenerated
     */
    public void setLimitspeed(String limitspeed) {
        this.limitspeed = limitspeed == null ? null : limitspeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.chedaowidth
     *
     * @return the value of emdata.chedaowidth
     *
     * @mbggenerated
     */
    public String getChedaowidth() {
        return chedaowidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.chedaowidth
     *
     * @param chedaowidth the value for emdata.chedaowidth
     *
     * @mbggenerated
     */
    public void setChedaowidth(String chedaowidth) {
        this.chedaowidth = chedaowidth == null ? null : chedaowidth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.luJianWidth
     *
     * @return the value of emdata.luJianWidth
     *
     * @mbggenerated
     */
    public String getLujianwidth() {
        return lujianwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.luJianWidth
     *
     * @param lujianwidth the value for emdata.luJianWidth
     *
     * @mbggenerated
     */
    public void setLujianwidth(String lujianwidth) {
        this.lujianwidth = lujianwidth == null ? null : lujianwidth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.bianYuanXianle
     *
     * @return the value of emdata.bianYuanXianle
     *
     * @mbggenerated
     */
    public String getBianyuanxianle() {
        return bianyuanxianle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.bianYuanXianle
     *
     * @param bianyuanxianle the value for emdata.bianYuanXianle
     *
     * @mbggenerated
     */
    public void setBianyuanxianle(String bianyuanxianle) {
        this.bianyuanxianle = bianyuanxianle == null ? null : bianyuanxianle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.zhongyanwidht
     *
     * @return the value of emdata.zhongyanwidht
     *
     * @mbggenerated
     */
    public String getZhongyanwidht() {
        return zhongyanwidht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.zhongyanwidht
     *
     * @param zhongyanwidht the value for emdata.zhongyanwidht
     *
     * @mbggenerated
     */
    public void setZhongyanwidht(String zhongyanwidht) {
        this.zhongyanwidht = zhongyanwidht == null ? null : zhongyanwidht.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.zhongXinXian
     *
     * @return the value of emdata.zhongXinXian
     *
     * @mbggenerated
     */
    public String getZhongxinxian() {
        return zhongxinxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.zhongXinXian
     *
     * @param zhongxinxian the value for emdata.zhongXinXian
     *
     * @mbggenerated
     */
    public void setZhongxinxian(String zhongxinxian) {
        this.zhongxinxian = zhongxinxian == null ? null : zhongxinxian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.chedaoxianbj
     *
     * @return the value of emdata.chedaoxianbj
     *
     * @mbggenerated
     */
    public String getChedaoxianbj() {
        return chedaoxianbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.chedaoxianbj
     *
     * @param chedaoxianbj the value for emdata.chedaoxianbj
     *
     * @mbggenerated
     */
    public void setChedaoxianbj(String chedaoxianbj) {
        this.chedaoxianbj = chedaoxianbj == null ? null : chedaoxianbj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.jiaotongkzlx
     *
     * @return the value of emdata.jiaotongkzlx
     *
     * @mbggenerated
     */
    public String getJiaotongkzlx() {
        return jiaotongkzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.jiaotongkzlx
     *
     * @param jiaotongkzlx the value for emdata.jiaotongkzlx
     *
     * @mbggenerated
     */
    public void setJiaotongkzlx(String jiaotongkzlx) {
        this.jiaotongkzlx = jiaotongkzlx == null ? null : jiaotongkzlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.zhuchedaoshu
     *
     * @return the value of emdata.zhuchedaoshu
     *
     * @mbggenerated
     */
    public String getZhuchedaoshu() {
        return zhuchedaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.zhuchedaoshu
     *
     * @param zhuchedaoshu the value for emdata.zhuchedaoshu
     *
     * @mbggenerated
     */
    public void setZhuchedaoshu(String zhuchedaoshu) {
        this.zhuchedaoshu = zhuchedaoshu == null ? null : zhuchedaoshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.jiaochajiedaoshu
     *
     * @return the value of emdata.jiaochajiedaoshu
     *
     * @mbggenerated
     */
    public String getJiaochajiedaoshu() {
        return jiaochajiedaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.jiaochajiedaoshu
     *
     * @param jiaochajiedaoshu the value for emdata.jiaochajiedaoshu
     *
     * @mbggenerated
     */
    public void setJiaochajiedaoshu(String jiaochajiedaoshu) {
        this.jiaochajiedaoshu = jiaochajiedaoshu == null ? null : jiaochajiedaoshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.WorkPlaceR
     *
     * @return the value of emdata.WorkPlaceR
     *
     * @mbggenerated
     */
    public String getWorkplacer() {
        return workplacer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.WorkPlaceR
     *
     * @param workplacer the value for emdata.WorkPlaceR
     *
     * @mbggenerated
     */
    public void setWorkplacer(String workplacer) {
        this.workplacer = workplacer == null ? null : workplacer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.Worktype
     *
     * @return the value of emdata.Worktype
     *
     * @mbggenerated
     */
    public String getWorktype() {
        return worktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.Worktype
     *
     * @param worktype the value for emdata.Worktype
     *
     * @mbggenerated
     */
    public void setWorktype(String worktype) {
        this.worktype = worktype == null ? null : worktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.havepeople
     *
     * @return the value of emdata.havepeople
     *
     * @mbggenerated
     */
    public String getHavepeople() {
        return havepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.havepeople
     *
     * @param havepeople the value for emdata.havepeople
     *
     * @mbggenerated
     */
    public void setHavepeople(String havepeople) {
        this.havepeople = havepeople == null ? null : havepeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emdata.xianChangZhifa
     *
     * @return the value of emdata.xianChangZhifa
     *
     * @mbggenerated
     */
    public String getXianchangzhifa() {
        return xianchangzhifa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emdata.xianChangZhifa
     *
     * @param xianchangzhifa the value for emdata.xianChangZhifa
     *
     * @mbggenerated
     */
    public void setXianchangzhifa(String xianchangzhifa) {
        this.xianchangzhifa = xianchangzhifa == null ? null : xianchangzhifa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", emnumber=").append(emnumber);
        sb.append(", routeposition=").append(routeposition);
        sb.append(", pengzhuangleixing=").append(pengzhuangleixing);
        sb.append(", lijiaoquyu=").append(lijiaoquyu);
        sb.append(", jcktype=").append(jcktype);
        sb.append(", teshuposition=").append(teshuposition);
        sb.append(", tianqicondition=").append(tianqicondition);
        sb.append(", zhaomingcondition=").append(zhaomingcondition);
        sb.append(", lumiancondition=").append(lumiancondition);
        sb.append(", lumianlev=").append(lumianlev);
        sb.append(", limitspeed=").append(limitspeed);
        sb.append(", chedaowidth=").append(chedaowidth);
        sb.append(", lujianwidth=").append(lujianwidth);
        sb.append(", bianyuanxianle=").append(bianyuanxianle);
        sb.append(", zhongyanwidht=").append(zhongyanwidht);
        sb.append(", zhongxinxian=").append(zhongxinxian);
        sb.append(", chedaoxianbj=").append(chedaoxianbj);
        sb.append(", jiaotongkzlx=").append(jiaotongkzlx);
        sb.append(", zhuchedaoshu=").append(zhuchedaoshu);
        sb.append(", jiaochajiedaoshu=").append(jiaochajiedaoshu);
        sb.append(", workplacer=").append(workplacer);
        sb.append(", worktype=").append(worktype);
        sb.append(", havepeople=").append(havepeople);
        sb.append(", xianchangzhifa=").append(xianchangzhifa);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Emdata other = (Emdata) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmnumber() == null ? other.getEmnumber() == null : this.getEmnumber().equals(other.getEmnumber()))
            && (this.getRouteposition() == null ? other.getRouteposition() == null : this.getRouteposition().equals(other.getRouteposition()))
            && (this.getPengzhuangleixing() == null ? other.getPengzhuangleixing() == null : this.getPengzhuangleixing().equals(other.getPengzhuangleixing()))
            && (this.getLijiaoquyu() == null ? other.getLijiaoquyu() == null : this.getLijiaoquyu().equals(other.getLijiaoquyu()))
            && (this.getJcktype() == null ? other.getJcktype() == null : this.getJcktype().equals(other.getJcktype()))
            && (this.getTeshuposition() == null ? other.getTeshuposition() == null : this.getTeshuposition().equals(other.getTeshuposition()))
            && (this.getTianqicondition() == null ? other.getTianqicondition() == null : this.getTianqicondition().equals(other.getTianqicondition()))
            && (this.getZhaomingcondition() == null ? other.getZhaomingcondition() == null : this.getZhaomingcondition().equals(other.getZhaomingcondition()))
            && (this.getLumiancondition() == null ? other.getLumiancondition() == null : this.getLumiancondition().equals(other.getLumiancondition()))
            && (this.getLumianlev() == null ? other.getLumianlev() == null : this.getLumianlev().equals(other.getLumianlev()))
            && (this.getLimitspeed() == null ? other.getLimitspeed() == null : this.getLimitspeed().equals(other.getLimitspeed()))
            && (this.getChedaowidth() == null ? other.getChedaowidth() == null : this.getChedaowidth().equals(other.getChedaowidth()))
            && (this.getLujianwidth() == null ? other.getLujianwidth() == null : this.getLujianwidth().equals(other.getLujianwidth()))
            && (this.getBianyuanxianle() == null ? other.getBianyuanxianle() == null : this.getBianyuanxianle().equals(other.getBianyuanxianle()))
            && (this.getZhongyanwidht() == null ? other.getZhongyanwidht() == null : this.getZhongyanwidht().equals(other.getZhongyanwidht()))
            && (this.getZhongxinxian() == null ? other.getZhongxinxian() == null : this.getZhongxinxian().equals(other.getZhongxinxian()))
            && (this.getChedaoxianbj() == null ? other.getChedaoxianbj() == null : this.getChedaoxianbj().equals(other.getChedaoxianbj()))
            && (this.getJiaotongkzlx() == null ? other.getJiaotongkzlx() == null : this.getJiaotongkzlx().equals(other.getJiaotongkzlx()))
            && (this.getZhuchedaoshu() == null ? other.getZhuchedaoshu() == null : this.getZhuchedaoshu().equals(other.getZhuchedaoshu()))
            && (this.getJiaochajiedaoshu() == null ? other.getJiaochajiedaoshu() == null : this.getJiaochajiedaoshu().equals(other.getJiaochajiedaoshu()))
            && (this.getWorkplacer() == null ? other.getWorkplacer() == null : this.getWorkplacer().equals(other.getWorkplacer()))
            && (this.getWorktype() == null ? other.getWorktype() == null : this.getWorktype().equals(other.getWorktype()))
            && (this.getHavepeople() == null ? other.getHavepeople() == null : this.getHavepeople().equals(other.getHavepeople()))
            && (this.getXianchangzhifa() == null ? other.getXianchangzhifa() == null : this.getXianchangzhifa().equals(other.getXianchangzhifa()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emdata
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmnumber() == null) ? 0 : getEmnumber().hashCode());
        result = prime * result + ((getRouteposition() == null) ? 0 : getRouteposition().hashCode());
        result = prime * result + ((getPengzhuangleixing() == null) ? 0 : getPengzhuangleixing().hashCode());
        result = prime * result + ((getLijiaoquyu() == null) ? 0 : getLijiaoquyu().hashCode());
        result = prime * result + ((getJcktype() == null) ? 0 : getJcktype().hashCode());
        result = prime * result + ((getTeshuposition() == null) ? 0 : getTeshuposition().hashCode());
        result = prime * result + ((getTianqicondition() == null) ? 0 : getTianqicondition().hashCode());
        result = prime * result + ((getZhaomingcondition() == null) ? 0 : getZhaomingcondition().hashCode());
        result = prime * result + ((getLumiancondition() == null) ? 0 : getLumiancondition().hashCode());
        result = prime * result + ((getLumianlev() == null) ? 0 : getLumianlev().hashCode());
        result = prime * result + ((getLimitspeed() == null) ? 0 : getLimitspeed().hashCode());
        result = prime * result + ((getChedaowidth() == null) ? 0 : getChedaowidth().hashCode());
        result = prime * result + ((getLujianwidth() == null) ? 0 : getLujianwidth().hashCode());
        result = prime * result + ((getBianyuanxianle() == null) ? 0 : getBianyuanxianle().hashCode());
        result = prime * result + ((getZhongyanwidht() == null) ? 0 : getZhongyanwidht().hashCode());
        result = prime * result + ((getZhongxinxian() == null) ? 0 : getZhongxinxian().hashCode());
        result = prime * result + ((getChedaoxianbj() == null) ? 0 : getChedaoxianbj().hashCode());
        result = prime * result + ((getJiaotongkzlx() == null) ? 0 : getJiaotongkzlx().hashCode());
        result = prime * result + ((getZhuchedaoshu() == null) ? 0 : getZhuchedaoshu().hashCode());
        result = prime * result + ((getJiaochajiedaoshu() == null) ? 0 : getJiaochajiedaoshu().hashCode());
        result = prime * result + ((getWorkplacer() == null) ? 0 : getWorkplacer().hashCode());
        result = prime * result + ((getWorktype() == null) ? 0 : getWorktype().hashCode());
        result = prime * result + ((getHavepeople() == null) ? 0 : getHavepeople().hashCode());
        result = prime * result + ((getXianchangzhifa() == null) ? 0 : getXianchangzhifa().hashCode());
        return result;
    }
}